# GitLab CI/CD configuration for Cooking Helper
image: node:16

# Cache node_modules for faster builds
cache:
  paths:
    - node_modules/

# Define stages
stages:
  - install
  - test
  - build
  - deploy

# Install dependencies
install_dependencies:
  stage: install
  script:
    - npm ci
  cache:
    paths:
      - node_modules/
    policy: pull-push

# Run tests (if you add them later)
# test_app:
#   stage: test
#   script:
#     - npm test
#   dependencies:
#     - install_dependencies

# Build the application
build_app:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 hour
  dependencies:
    - install_dependencies

# Deploy to GitLab Pages (optional)
deploy_pages:
  stage: deploy
  script:
    - echo "Deploying to GitLab Pages"
    - cp -r build/* public/
  artifacts:
    paths:
      - public/
  only:
    - main
  dependencies:
    - build_app

# Manual deployment (for production)
deploy_manual:
  stage: deploy
  script:
    - echo "Manual deployment triggered"
    - echo "Build artifacts are available in the build/ directory"
  when: manual
  only:
    - main
  dependencies:
    - build_app
