name: Deploy React to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js 16
      uses: actions/setup-node@v4
      with:
        node-version: '16'
        
    - name: Install dependencies
      run: |
        npm install --legacy-peer-deps
        
    - name: Build React app
      run: |
        npm run build
      env:
        CI: false
        NODE_OPTIONS: "--max_old_space_size=4096"
        
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        publish_branch: gh-pages
